import { GunConfig, MissileConfig } from '../types';

export const GUNS_LIST: GunConfig[] = [
  {
    id: 'gsh301',
    name: {
      uk: 'ГШ-30-1 (30-мм)',
      ru: 'ГШ-30-1 (30-мм)',
      en: 'GSh-30-1 (30mm)',
    },
    type: 'Автоматична авіапушка',
    caliber: '30×165 мм',
    description: {
      uk: 'Базова 30-мм одноствольна авіаційна гармата з високою початковою швидкістю снаряда та нищівною кінетичною силою.',
      ru: 'Базовая 30-мм авиапушка с высокой начальной скоростью снаряда и сокрушительной кинетической мощью.',
      en: 'Standard 30mm single-barrel autocannon delivering heavy kinetic impacts against drone airframes.',
    },
    unlockLevel: 1,
    unlockCost: 0,
    damage: 35,
    fireRate: 14, // rounds/sec
    heatPerShot: 0.05,
    coolRate: 0.45,
    bulletSpeed: 750,
    color: '#fbbf24', // Amber tracer
  },
  {
    id: 'gsh23_twin',
    name: {
      uk: 'ГШ-23Л Спарена (23-мм)',
      ru: 'ГШ-23Л Сдвоенная (23-мм)',
      en: 'GSh-23L Twin-Barrel (23mm)',
    },
    type: 'Спарена скорострільна пушка',
    caliber: '23×115 мм',
    description: {
      uk: 'Двоствольна схема Гаста забезпечує підвищений темп стрільби до 3400 постр/хв, створюючи щільну завісу куль проти роїв шахедів.',
      ru: 'Двуствольная схема Гаста обеспечивает высокий темп стрельбы, создавая плотную завесу огня против роев шахедов.',
      en: 'Twin Gast-principle barrels pumping out a dense curtain of fire against drone swarms.',
    },
    unlockLevel: 3,
    unlockCost: 950,
    damage: 28,
    fireRate: 22,
    heatPerShot: 0.035,
    coolRate: 0.5,
    bulletSpeed: 780,
    color: '#f97316', // Orange fire tracer
  },
  {
    id: 'vulcan_m61',
    name: {
      uk: 'M61A1 Vulcan (20-мм)',
      ru: 'M61A1 Vulcan (20-мм)',
      en: 'M61A1 Vulcan Rotary (20mm)',
    },
    type: 'Шестиствольний роторний кулемет',
    caliber: '20×102 мм',
    description: {
      uk: 'Шестиствольна ротаційна гармата стандарту НАТО з гідравлічним приводом. 6000 пострілів на хвилину буквально розпилюють шахеди на друзки.',
      ru: 'Шестиствольная роторная пушка стандарта НАТО. 6000 выстрелов в минуту буквально распиливают шахеды на части.',
      en: 'Hydraulic 6-barrel Gatling autocannon firing 6,000 rounds per minute. Devastating shredder against airborne kamikazes.',
    },
    unlockLevel: 6,
    unlockCost: 2400,
    damage: 32,
    fireRate: 30,
    heatPerShot: 0.025,
    coolRate: 0.6,
    bulletSpeed: 850,
    color: '#38bdf8', // Blue-white NATO API tracer
  },
  {
    id: 'oerlikon_35',
    name: {
      uk: 'Skyranger AHEAD (35-мм)',
      ru: 'Skyranger AHEAD (35-мм)',
      en: 'Skyranger 35mm AHEAD',
    },
    type: 'Важка револьверна гармата',
    caliber: '35×228 мм Програмована',
    description: {
      uk: 'Важка гармата з осколковими снарядами AHEAD, які детонують перед шахедом хмарою вольфрамових вражаючих елементів.',
      ru: 'Тяжелая пушка с программируемыми снарядами AHEAD, детонирующими перед дроном облаком вольфрамовых суббоеприпасов.',
      en: 'Heavy 35mm revolver cannon with programmable airburst submunitions for guaranteed drone obliteration.',
    },
    unlockLevel: 9,
    unlockCost: 4800,
    damage: 58,
    fireRate: 16,
    heatPerShot: 0.055,
    coolRate: 0.55,
    bulletSpeed: 920,
    color: '#eab308', // Brilliant yellow-gold tracer
  },
  {
    id: 'plasma_railgun',
    name: {
      uk: 'Рельсотрон «Грім-X» 6G',
      ru: 'Рельсотрон «Гром-X» 6G',
      en: 'Grom-X Plasma Railgun 6G',
    },
    type: 'Імпульсний електромагнітний випромінювач',
    caliber: 'Квантовий плазмовий промінь',
    description: {
      uk: 'ЗБРОЯ 6-ГО ПОКОЛІННЯ! Гіперзвуковий електромагнітний імпульс миттєво спопеляє будь-яку повітряну ціль та пробиває стрій навиліт.',
      ru: 'ОРУЖИЕ 6-ГО ПОКОЛЕНИЯ! Гиперзвуковой электромагнитный импульс мгновенно испепеляет любую воздушную цель насквозь.',
      en: '6TH-GEN SUPERWEAPON! Fires hyper-velocity plasma-accelerated darts that pierce and disintegrate any airborne target.',
    },
    unlockLevel: 12,
    unlockCost: 8500,
    damage: 95,
    fireRate: 20,
    heatPerShot: 0.03,
    coolRate: 0.8,
    bulletSpeed: 1400,
    color: '#00f0ff', // Cyber cyan plasma beam
    isEnergy: true,
  },
];

export const MISSILES_LIST: MissileConfig[] = [
  {
    id: 'r73',
    name: {
      uk: 'Р-73 «Archer»',
      ru: 'Р-73 «Archer»',
      en: 'R-73 Archer IR',
    },
    type: 'Керована ракета ближнього бою',
    guidance: 'Інфрачервона ГСН',
    description: {
      uk: 'Високоманеврена ракета «повітря-повітря» з газодинамічним керуванням. Ідеальна для швидкого перехоплення шахедів за тепловим слідом двигуна.',
      ru: 'Высокоманевренная ракета ближнего боя. Идеальна для быстрого захвата шахедов по тепловому следу двигателя.',
      en: 'Highly agile all-aspect infrared missile with thrust vectoring, tracking drone thermal signatures.',
    },
    unlockLevel: 1,
    unlockCost: 0,
    damage: 130,
    blastRadius: 35,
    maxSpeed: 450,
    turnRate: 3.2,
    lockTime: 1.1,
    lockRange: 600,
    capacityBonus: 0,
    color: '#ef4444',
  },
  {
    id: 'aim9x',
    name: {
      uk: 'AIM-9X Sidewinder',
      ru: 'AIM-9X Sidewinder',
      en: 'AIM-9X Sidewinder Block II',
    },
    type: 'Високоточна ракета НАТО',
    guidance: 'Тепловізійна матрична ГСН',
    description: {
      uk: 'Надсучасна ракета з матричною тепловізійною головкою, стійка до теплових пасток. Захоплює навіть слабонагріті мотори шахедів.',
      ru: 'Сверхсовременная ракета с тепловизионной головкой самонаведения. Мгновенно захватывает даже малозаметные дроны.',
      en: 'Modern imaging infrared seeker with 90-degree off-boresight capability. Locks onto faint thermal signatures.',
    },
    unlockLevel: 4,
    unlockCost: 1400,
    damage: 165,
    blastRadius: 42,
    maxSpeed: 520,
    turnRate: 4.2,
    lockTime: 0.85,
    lockRange: 750,
    capacityBonus: 1,
    color: '#06b6d4',
  },
  {
    id: 'r27er',
    name: {
      uk: 'Р-27ЕР «Alamo-C»',
      ru: 'Р-27ЭР «Alamo-C»',
      en: 'R-27ER Extended Range',
    },
    type: 'Далекобійна ракета перехоплення',
    guidance: 'Напівактивна радіолокаційна',
    description: {
      uk: 'Потужний ракетний двигун та 39-кг осколково-фугасна бойова частина. Знищує крилаті ракети та групи шахедів на великій дистанції.',
      ru: 'Мощный ракетный двигатель и 39-кг осколочно-фугасная БЧ. Уничтожает крылатые ракеты и группы шахедов на огромной дистанции.',
      en: 'Long-range interceptor missile with heavy explosive warhead. Perfect for long-distance cruise missile takedowns.',
    },
    unlockLevel: 7,
    unlockCost: 3200,
    damage: 220,
    blastRadius: 55,
    maxSpeed: 640,
    turnRate: 2.8,
    lockTime: 0.75,
    lockRange: 950,
    capacityBonus: 1,
    color: '#8b5cf6',
  },
  {
    id: 'iris_t',
    name: {
      uk: 'IRIS-T Air Superiority',
      ru: 'IRIS-T Air Superiority',
      en: 'IRIS-T Precision Air',
    },
    type: 'Надманеврена протиповітряна ракета',
    guidance: 'Інфрачервона з оптичним ШІ',
    description: {
      uk: 'Німецька надточна ракета з інтелектуальним розпізнаванням контурів цілей. 100% точність по низьковисотних цілях та крилатих ракетах.',
      ru: 'Немецкая сверхточная ракета с интеллектуальным распознаванием силуэтов целей. Исключительная точность против дронов.',
      en: 'German thrust-vectored precision dogfight missile with target contour recognition AI. Extreme kill probability.',
    },
    unlockLevel: 10,
    unlockCost: 5500,
    damage: 260,
    blastRadius: 50,
    maxSpeed: 600,
    turnRate: 5.5,
    lockTime: 0.55,
    lockRange: 900,
    capacityBonus: 2,
    color: '#10b981',
  },
  {
    id: 'trembita_hypersonic',
    name: {
      uk: '«Трембіта-X» Ройова Гіперзвукова',
      ru: '«Трембита-X» Роевая Гиперзвуковая',
      en: 'Trembita-X Hypersonic Swarm',
    },
    type: 'Гіперзвукова інтелектуальна ракета 6G',
    guidance: 'Квантова когерентна РЛС',
    description: {
      uk: 'РАКЕТА 6-ГО ПОКОЛІННЯ! Розвиває швидкість 5+ Махів, детонує мікрохвильовим електромагнітним вибухом, збиваючи одночасно кілька шахедів поруч.',
      ru: 'РАКЕТА 6-ГО ПОКОЛЕНИЯ! Скорость 5+ Махов, микроволновой электромагнитный подрыв, сбивает сразу несколько целей в радиусе.',
      en: '6TH-GEN HYPERSONIC WEAPON! Mach 5+ velocity with electromagnetic airburst that eradicates multiple drones clustered together.',
    },
    unlockLevel: 12,
    unlockCost: 9500,
    damage: 350,
    blastRadius: 75,
    maxSpeed: 850,
    turnRate: 6.0,
    lockTime: 0.35,
    lockRange: 1200,
    capacityBonus: 4,
    color: '#00f0ff',
    isHypersonic: true,
  },
];
